version: '3.7'

services:
  mongodb:
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: apartment
      MONGO_INITDB_ROOT_PASSWORD: apartment
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db

  server:
    build:
      context: .
      dockerfile: cmd/server/Dockerfile
    ports:
      - "9000:9000"
    environment:
      MONGO_URL: mongodb://apartment:apartment@mongodb:27017
      AUTH_TOKEN: ${AUTH_TOKEN}
    depends_on:
      - mongodb
    healthcheck:
      test: ["CMD-SHELL", "grpc_health_probe -addr=:9005 -service=server"]
      interval: 30s
      timeout: 10s
      start_period: 60s
    restart: always

  message:
    build:
      context: .
      dockerfile: cmd/message/Dockerfile
    ports:
      - "9001:9001"
    environment:
      MONGO_URL: mongodb://apartment:apartment@mongodb:27017
      AUTH_TOKEN: ${AUTH_TOKEN}
    healthcheck:
      test: ["CMD-SHELL", "grpc_health_probe -addr=:9005 -service=message"]
      interval: 30s
      timeout: 10s
      start_period: 60s
    depends_on:
      server:
          condition: service_healthy
    restart: always

  client:
    build:
      context: .
      dockerfile: cmd/client/Dockerfile
    environment:
      SERVER_URL: server:9000
      MESSAGE_URL: message:9001
      TELEGRAM_BOT_SECRET: ${TELEGRAM_BOT_SECRET}
      AUTH_TOKEN: ${AUTH_TOKEN}
    depends_on:
      server:
        condition: service_healthy
      message:
        condition: service_healthy
    restart: always

volumes:
  mongo: