services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: apartment
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db 
    restart: always

  server:
    image: irbgeo/apartment-bot-server:${SERVER_VERSION}
    container_name: server
    environment:
      MONGO_URL: mongodb://apartment:${MONGO_PASSWORD}@mongodb:27017/
      AUTH_TOKEN: ${AUTH_TOKEN}
      MY_HOME_MAX_PAGE: 30
    ports:
      - "80:80"
      - "9000:9000"
    depends_on:
      - mongodb
    healthcheck:
      test: ["CMD-SHELL", "grpc_health_probe -addr=:9005 -service=server"]
      interval: 30s
      timeout: 10s
      start_period: 60s
    restart: always

  client:
    image: irbgeo/apartment-bot-client:${CLIENT_VERSION}
    container_name: client
    environment:
      SERVER_URL: server:9000
      MESSAGE_URL: message:9001
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      AUTH_TOKEN: ${AUTH_TOKEN}
      TELEGRAM_BOT_DISABLED_PARAMS: ""
    depends_on:
      server:
        condition: service_healthy
    restart: always
