---
- name: Install Git, Golang and setup project
  hosts: all
  become: true
  vars_files:
    - ../vars/secret.yaml

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      tags: install_packages

    - name: Install Git
      apt:
        name: git
        state: present
      tags: install_packages

    - name: Download latest Go version
      get_url:
        url: https://go.dev/dl/go1.23.4.linux-amd64.tar.gz
        dest: /tmp/go.tar.gz
        mode: "0644"
      tags: install_golang

    - name: Remove old Go installation if exists
      file:
        path: /usr/local/go
        state: absent
      tags: install_golang

    - name: Extract Go archive
      unarchive:
        src: /tmp/go.tar.gz
        dest: /usr/local
        remote_src: yes
      tags: install_golang

    - name: Add Go paths to /root/.bashrc
      blockinfile:
        path: /root/.bashrc
        block: |
          export GOROOT=/usr/local/go
          export GOPATH=$HOME/go
          export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
        marker: "# {mark} ANSIBLE MANAGED BLOCK - GOLANG"
      tags: configure_golang

    - name: Clean up downloaded archive
      file:
        path: /tmp/go.tar.gz
        state: absent
      tags: install_golang

    - name: Clean project directory
      file:
        path: "{{ project_path }}"
        state: absent
      tags: setup_project

    - name: Create project directory
      file:
        path: "{{ project_path }}"
        state: directory
        mode: "0755"
      tags: setup_project

    - name: Clone apartment-bot repository
      git:
        repo: git@github.com:irbgeo/apartment-bot.git
        dest: "{{ project_path }}"
        accept_hostkey: yes
        key_file: /root/.ssh/id_rsa
      become: true
      tags: setup_project

    - name: Copy .vscode directory
      copy:
        src: "../../.vscode"
        dest: "{{ project_path }}/"
        mode: "0644"
      tags: copy_files

    - name: Copy .env.secret file
      copy:
        src: "../../.env.secret"
        dest: "{{ project_path }}/.env.secret"
        mode: "0644"
      tags: copy_files

    - name: Verify Go installation
      shell: /usr/local/go/bin/go version
      register: go_version
      changed_when: false
      tags: verify_installation

    - name: Display Go version
      debug:
        var: go_version.stdout
      tags: verify_installation

    - name: Run mongo
      command: run-mongo
      args:
        chdir: "{{ project_path }}"
      environment:
        MONGO_PASSWORD: "{{ mongo_password }}"
      tags: run
