---
- hosts: server
  become: true
  vars_files:
    - deploy/vars/secret.yaml
  tasks:
    - name: Copy files to server
      copy:
        src: "{{ playbook_dir }}/../../{{ item.src }}"
        dest: "{{ project_path }}/{{ item.src }}"
        mode: "0644"
      with_items:
        - { src: "docker-compose.yaml" }
        - { src: "Makefile" }
      tags: copy_files

    - name: Run application
      command: make run
      args:
        chdir: "{{ project_path }}"
      environment:
        TELEGRAM_BOT_TOKEN: "{{ telegram_bot_token }}"
        AUTH_TOKEN: "{{ auth_token }}"
        MONGO_PASSWORD: "{{ mongo_password }}"
        SERVER_VERSION: "{{ server_version }}"
        CLIENT_VERSION: "{{ client_version }}"
      tags: run
