---
- hosts: server
  become: true
  vars_files:
    - deploy/vars/secret.yaml
  tasks:
    - name: Run application
      command: make run
      args:
        chdir: "{{ project_path }}"
      environment:
        TELEGRAM_BOT_TOKEN: "{{ telegram_bot_token }}"
        AUTH_TOKEN: "{{ auth_token }}"
        MONGO_PASSWORD: "{{ mongo_password }}"
        SERVER_VERSION: "{{ server_version }}"
        CLIENT_VERSION: "{{ client_version }}"
      tags: run
