---
- hosts: server
  become: true
  vars_files:
    - ../vars/secret.yaml
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      tags: install_packages

    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
          - make
        state: present
      tags: install_packages

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      tags: install_packages

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present
      tags: install_packages

    - name: Install Docker
      apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
      tags: install_packages

    - name: Create apartment-bot directory
      file:
        path: "{{ project_path }}"
        state: directory
        mode: "0755"
      tags: copy_files

    - name: Copy files to server
      copy:
        src: "{{ playbook_dir }}/../../{{ item.src }}"
        dest: "{{ project_path }}/{{ item.src }}"
        mode: "0644"
      with_items:
        - { src: "docker-compose.yaml" }
        - { src: "Makefile" }
      tags: copy_files

    - name: Log into Docker registry
      docker_login:
        username: "{{ docker_username }}"
        password: "{{ docker_password }}"
        state: present
      tags: docker_login
